---
title: "Example"
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

## Accessing test files 
```{r setup, eval=FALSE}
#Pick one file from the bunch
raw_dbf <- system.file("extdata", "liposomes_214.dbf", package = "normfluodbf", mustWork = TRUE)

#Pass the file through the function
norm_dbf <- normfluodbf::norm_tidy_dbf(raw_dbf)

#Analyze post-normalization (based on liposomes_214.dbf)
yvars <- c("A01","A02","A03") #sequence should be test,NC,PC
xvar <- c("Time","Cycle_Number")
xl <- c(1,40)
yl <- c(0,1)

#geom_line and geom_point functions must be used this way to have a line with dot plots.
gg_plot_triplets <- function(df, x, y_list, xlim, ylim){
  library(ggplot2)
  p1 <- ggplot(df, aes(x=.data[[x[1]]])) +
    geom_point(aes(y=.data[[y_list[1]]]), size=3, color="blue") +
    geom_point(aes(y=.data[[y_list[2]]]), size=3, color="red") +
    geom_point(aes(y=.data[[y_list[3]]]), size=3, color="green") +
    geom_line(aes(y=.data[[y_list[1]]], color="Test"), size = 0.8) +
    geom_line(aes(y=.data[[y_list[2]]], color="Negative Control"),size = 0.8) +
    geom_line(aes(y=.data[[y_list[3]]], color="Positivetive Control"), size = 0.8) +
    dark_mode()+  coord_cartesian(xlim = xlim) +  coord_cartesian(ylim=ylim) +
    labs(title = 'NavAb Liposome Flux Assay',
         x = 'Cycle_No', y='Normalized Fluorescence', color='Sample Type')
  p1
}

gg_plot_triplets_sym(norm_dbf,x=xvar,y_list=yvars,xlim=xl,ylim=yl)
```
